### PR TITLE
ENH: refreshes convolve timings

### PR DESCRIPTION
**Pull request by stsievert**
We've speeded up scipy.signal.convolve.

In scipy/scipy#5291 we call `np.convolve` when the input is 1D.

In scipy/scipy#5608 we decide what convolution method is fastest. We decide among fftconvolve, np.convolve for 1D and the old scipy.signal.convolve implementation. This code is not merged into master yet.

### CODE REVIEW

**Comment by stsievert** [comment]
And this is the refreshed graph:

screen shot 2016-04-09 at 10 47 06 pm

**Comment by stsievert** [comment]
Do I have to generate the HTML files too? I only made changes to the notebook.

**Comment by pv** [comment]
No, readthedocs should do it automatically

**Comment by stsievert** [comment]
I ask because it's been 7 hours and readthedocs still hasn't updated.

**Comment by pv** [comment]
was due to semantics change in "jupyter nbconvert". should be ok now.

**Pull request merged**
